/** @type {import('prettier').Config} */ module.exports = {
	arrowParens: "always",
	printWidth: 80,
	singleQuote: false,
	jsxSingleQuote: false,
	semi: true,
	trailingComma: "all",
	tabWidth: 2,
	endOfLine: "lf",
	importOrder: [
		"^(react/(.*)$)|^(react$)",
		"^(next/(.*)$)|^(next$)",
		"<THIRD_PARTY_MODULES>",
		"",
		"^types$",
		"^@local/(.*)$",
		"^@/config/(.*)$",
		"^@/lib/(.*)$",
		"^@/components/(.*)$",
		"^@/styles/(.*)$",
		"^[./]",
	],
	importOrderSeparation: false,
	importOrderSortSpecifiers: true,
	importOrderBuiltinModulesToTop: true,
	importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
	importOrderMergeDuplicateImports: true,
	importOrderCombineTypeAndValueImports: true,
	plugins: [
		require.resolve("prettier-plugin-tailwindcss"),
		require.resolve("@ianvs/prettier-plugin-sort-imports"),
	],
	tailwindConfig: "./packages/config/tailwind",
};
